security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    superadmin:
                        password: password
                        roles: 'ROLE_SUPER_ADMIN'
                    admin:
                        password: password
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            provider: in_memory
            form_login:
                default_target_path: /login
                always_use_default_target_path: true
                require_previous_session: false
            logout: ~
            anonymous: true

    access_control:
      - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
