security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: password
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            provider: in_memory
            form_login:
                default_target_path: /
                always_use_default_target_path: true
            logout: ~
            anonymous: true

    access_control:
      - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
      - { path: ^/, roles: [ROLE_ADMIN] }
