api:
    prefix: /api
    resource: @PuszekPuszekAdminAdminBundle/Resources/config/api_routing.yml

puszek_admin_homepage:
    path:     /
    defaults: { _controller: PuszekPuszekAdminAdminBundle:Dashboard:index }
